# 개발환경용 Dockerfile
FROM rust:1.89

# Install system dependencies
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    libmariadb-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install cargo-watch for hot reload
RUN cargo install cargo-watch

# Set working directory
WORKDIR /app

# copy data
COPY . .

ENV SQLX_OFFLINE=1
RUN cargo build

# Expose port
EXPOSE 1028

# Default command for development (hot reload)
CMD ["cargo-watch", "-i", "logs/**", "-x", "run"]
